### ISSUE TITLE
error when lists are empty

### ISSUE THREAD

**Issue by rob42** [yetu/ansible-apt#9]
In ansible 2.2 on kubuntu 16.04 I get an error for `apt_default_key_urls` and  `apt_default_repositories` when the lists are empty (default):
```
failed: [35.162.23.231] (item=apt_default_repositories) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "filename": null, 
            "install_python_apt": true, 
            "mode": null, 
            "repo": "apt_default_repositories", 
            "state": "present", 
            "update_cache": true, 
            "validate_certs": true
        }, 
        "module_name": "apt_repository"
    }, 
    "item": "apt_default_repositories", 
    "msg": "Invalid repository string: apt_default_repositories"
}
```
Problem is fixed by adding `when: apt_default_key_urls` to avoid empty lists, eg:
```
- name: APT | Make sure the default keys are added
  apt_key:
    url: "{{item}}"
    state: present
  with_items: apt_default_key_urls
  when: apt_default_key_urls

```
